--? 1. Modelo de Datos (BD)
CREATE TABLE PRODUCTOS_K (
    ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOMBRE VARCHAR2(100),
    PRECIO NUMBER(10,2),
    STOCK NUMBER
);

COMMIT;

-- datos prueba :. /
INSERT INTO PRODUCTOS_K (NOMBRE, PRECIO, STOCK) VALUES ('Laptop', 2500, 10);
INSERT INTO PRODUCTOS_K (NOMBRE, PRECIO, STOCK) VALUES ('Mouse', 50, 100);
INSERT INTO PRODUCTOS_K (NOMBRE, PRECIO, STOCK) VALUES ('Teclado', 120, 50);
COMMIT;